name: '[Dev] Deploy Hibro'
on:
  push:
    branches: [dev,master]
env:
  PROJECT_ID: endose-hibro
  RUN_REGION: asia-southeast1
  REPO_NAME: ${{ github.event.repository.name }}
  SA: ${{ secrets.SA_ENDOSE_HIBRO }}
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
jobs:
  deploy:
    runs-on: [hibro]
    steps:
      - uses: actions/checkout@v2
      # - uses: nelonoel/branch-name@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ env.SA }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: false
      - run: gcloud info
      - run: gcloud auth configure-docker
      - run: docker build -t artisandigitalasia/hibro:dev --build-arg APP_ENV=dev .
      - run: |
          chmod +x _deployment/hibro.sh
          _deployment/hibro.sh deploy hibro dev
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          username: 'hibro'
          channel: 'claris-deploy'
